apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    capability.tanzu.vmware.com/provides: |-
      [{
        "name": "gateway-api.se.ext.tanzu.com",
        "displayName": "Gateway Api CRDs",
        "description": "Provides the Gateway API CRDs as a workaround fot TKGm clusters",
        "vendor": "Tanzu Field",
        "tags": [ "networking" ],
        "groupVersionKinds": []
      }]
  creationTimestamp: null
  name: gateway-api.se.ext.tanzu.com.0.0.0
spec:
  refName: gateway-api.se.ext.tanzu.com
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3: null
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: gateway-api.se.ext.tanzu.com
spec:
  displayName: gateway-api
  longDescription: gateway-api.se.ext.tanzu.com
  shortDescription: gateway-api.se.ext.tanzu.com

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: gateway-api
spec:
  packageRef:
    refName: gateway-api.se.ext.tanzu.com
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: gateway-api-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
